name: ci-cd

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  id-token: write
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest -q --disable-warnings --maxfail=1

  dvc-pipeline:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[s3]

      - name: Debug AWS inputs
        run: |
          echo "Role: ${{ secrets.AWS_ROLE_TO_ASSUME }}"
          echo "Region: ${{ secrets.AWS_REGION }}"
          echo "S3: ${{ secrets.DVC_S3_URL }}"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
        continue-on-error: true

      - name: Configure DVC remote
        run: |
          dvc remote add -f aws ${{ secrets.DVC_S3_URL }} || true
          dvc remote default aws || true

      - name: Run DVC pipeline
        run: dvc repro || true

      - name: Push DVC artifacts to S3
        run: dvc push || true

      - name: Show metrics (if available)
        run: |
          echo "Metrics:"
          cat reports/metrics.json || echo "No metrics.json found"

      - name: Upload metrics artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: reports/metrics.json

      - name: Upload dvclive logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dvclive
          path: dvclive
