stages:
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
      - data/raw/train_data.csv
      - data/raw/test_data.csv
      - scripts/preprocess.py
    outs:
      - data/interim/train_processed.csv
      - data/interim/test_processed.csv

  vectorize:
    cmd: python scripts/vectorize.py
    deps:
      - data/interim/train_processed.csv
      - data/interim/test_processed.csv
      - scripts/vectorize.py
    outs:
      - data/processed/train_tfidf.csv
      - data/processed/test_tfidf.csv
      - data/interim/vectorizer.pkl

  train:
    cmd: python scripts/train_model.py
    deps:
      - data/processed/train_tfidf.csv
      - scripts/train_model.py
    outs:
      - model/model.pkl
      - model/vectorizer.pkl
      - reports/metrics.json
